CREATE DATABASE IF NOT EXISTS gerenciador DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE gerenciador;

CREATE TABLE IF NOT EXISTS itens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  quantidade INT NOT NULL DEFAULT 0,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;